### ISSUE TITLE
Cannot really pick a file

### ISSUE THREAD

**Issue by johnblommers** [ronniedroid/concessio#4]
When opening a file to check its permissions, the Concessio display does not change. The file name chosen is not displayed, nor are its permissions shown. Concessio just displays its standard dialog again.

This remains true even if we use Flatseal to allow access to user files.

No message emit in the console when we run Concessio from the command line:

`flatpak install flathub io.github.ronniedroid.concessio`

My system is a stock Pop!_OS system 22.04 no COSMIC DE running GNOME and Xorg.

**Comment by ronniedroid** [comment]
Concessio doesn't show the name of the file anywhere, maybe I should improve this. 

You don't need to allow access to all files.

Maybe I should add a toast message saying the file was opened. 

Try setting the permissions to 000, then open a file and check if you'll see a change.

**Comment by johnblommers** [comment]
> Try setting the permissions to 000, then open a file and check if you'll see a change.

I already did exactly this and the Concessio display does not reflect the 000 permissions

**Comment by ronniedroid** [comment]
I just tested and 000 permissions are reflected correctly and file opening works just fine.
Please send screenshots to showcase the issue your having so I may help.
