### ISSUE TITLE
missing Linux permissions: SUID, SGID, and sticky bit

### ISSUE THREAD

**Issue by ulefr01** [ronniedroid/concessio#6]
I am missing the Linux permissions: SUID, SGID, and sticky bit (>777)

**Comment by ronniedroid** [comment]
Thank you for noticing that, will make sure to add it in the next release.

Not sure how to deal with it in the toggles section though.

**Comment by ronniedroid** [comment]
Done, your feedback is appreciated.

**Comment by ulefr01** [comment]
Thank you very much
Franz Ulenaers
***@***.*** wrote:
Closed #6 <https://github.com/ronniedroid/concessio/issues/6> as completed.
