### ISSUE TITLE
Translation formatting issues

### ISSUE THREAD

**Issue by RobusTetus** [ronniedroid/concessio#9]
Today I noticed following issue with czech translation.
![Snímek obrazovky z 2024-09-21 16-17-39](https://github.com/user-attachments/assets/3a6a5a84-2826-43f0-a886-f398080b00fb)

Same artifact seems to be present in translated description in Gnome Software.
![Snímek obrazovky z 2024-09-21 16-17-58](https://github.com/user-attachments/assets/7cae6fdf-d45d-4f62-9a59-25117eaf6cfb)

This is present only in strings tied to Concessio project. Every other translated project is not having said artifacts.

**Comment by RobusTetus** [comment]
Upon further inspection, the strings in po/cs.po are clearly incorrectly formatted.

**Comment by ronniedroid** [comment]
I apologize, I do not know the language, but I should have checked.
